### ISSUE TITLE
Improve Singleton-Pattern in Factory

### ISSUE THREAD

**Issue by miho** [turpid-monkey/modelgen#3]
The current singleton-pattern is not safe:

```java
   public static ModelFactory instance()
   {
      if (instance==null) return instance = new ModelFactory(); else return instance;
   }
```

Enum-Singleton might be handy:

```java
enum {
  INSTANCE
}
```
or https://en.wikipedia.org/wiki/Singleton_pattern#cite_note-9

**Comment by turpid-monkey** [comment]
Like proposed, ModelFactory is now generated a enum, with a single enum constant INSTANCE.

Even though i'm not a friend of singleton pattern, I think it is practical as long as ModelFactory doesn't have state.
