### ISSUE TITLE
Name collision (should move implementations to impl subpackage)

### ISSUE THREAD

**Issue by miho** [turpid-monkey/modelgen#6]
Consider the following interfaces:

```java
public class Test {
  // ...
}
```
and

```java
public class TestObject {
  // ...
}
```

They will lead to the following impl Classes:

```
Test               => TestObject.java
TestObject         => TestObjectObject.java
```

**Problem:**

`TestObject` class from `Test` causes name collision with `TestObject` interface.

**Possible Solution:**

Move impl classes to `impl`subpackage.

**Comment by turpid-monkey** [comment]
Moved generated implementations to sub package ".impl". This should prevent 99% of name collisions that sane people might run into.

It's still possible to compromise the generated code with "TestObjectObject" and "TestObjectObjectObject", but that's rather insane.
